export const styleConfig = {
  base: {
    rootFontSizePx: 16,
    typographicScale: 1.25,
    gridUnitPx: 4,
    safeAreaSidePx: 24,
  },
  typography: {
    chapterTitle: { fontSizePx: 28, fontWeight: 600, lineHeightPx: 36 },
    topButton: { fontSizePx: 14, fontWeight: 500, lineHeightPx: 20 },
    narratorLabel: { fontSizePx: 14, fontWeight: 600, lineHeightPx: 20 },
    narratorText: { fontSizePx: 20, fontWeight: 400, lineHeightPx: 28 },
    dialogueName: { fontSizePx: 18, fontWeight: 600, lineHeightPx: 26 },
    dialogueText: { fontSizePx: 18, fontWeight: 400, lineHeightPx: 26 },
    emphasisText: { fontSizePx: 18, fontWeight: 400, lineHeightPx: 26 },
    bottomButton: { fontSizePx: 14, fontWeight: 500, lineHeightPx: 20 },
    secondaryLabel: { fontSizePx: 12, fontWeight: 500, lineHeightPx: 16 },
  },
  iconography: {
    sm: 16,
    md: 20,
    lg: 24,
    xl: 32,
  },
  layout: {
    headerHeightPx: 64,
    headerPaddingX: 24,
    headerGapPx: 16,
    narratorBarMinHeightPx: 56,
    narratorPaddingY: 12,
    narratorPaddingX: 20,
    dialoguePaddingY: 16,
    dialoguePaddingX: 20,
    dialogueRadiusPx: 8,
    dialogueGapPx: 24,
    dialogueMaxWidthPx: 420,
    bottomHeightPx: 80,
    bottomPaddingY: 16,
    bottomPaddingX: 24,
    bottomGapPx: 12,
  },
} as const;
